title: Validation in Java applications
description: Yet another brief guide for data validation
theme: jekyll-theme-cayman
show_downloads: false
locale: en-US
words_per_minute: 200
repository: dyakonoff/cuba-validation-examples